
services:
  expo:
    container_name: expo-build-vemitienda
    build:
      context: ./ # Especifica el directorio del contexto de construcción (donde está el Dockerfile)
      dockerfile: DockerfileBuild # Especifica el nombre del archivo Dockerfile a usar
    ports: # Specify port-forwarding
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      - ./:/app # Link host directory to container
      - nodemodules:/app/node_modules
    env_file: .env
    command: eas build --platform android --local --non-interactive

volumes:
  nodemodules: {}

# Con este se contruye el .aab. Solo debo escribir docker compose -f docker-compose-build.yml up --build